### PR TITLE
fixed bad naming

### PR DESCRIPTION
**Pull request by marcosdotps**

### CODE REVIEW

**Comment by mpenate** [comment]
Do IT!

**Comment by mpenate** [comment]
@runIT

**Comment by marcosdotps** [comment]
#RunIT

**Comment by marcosdotps** [comment]
#RunIT

**Comment by marcosdotps** [comment]
#RunIT

**Comment by marcosdotps** [comment]
DO-IT!

**Comment by marcosdotps** [comment]
:rocket: [starting ci integration test job]( https://github.com/mpenate/stokkolm/actions/runs/792251269)

**Pull request closed without merging**
